[server]
# Désactiver le watchdog pour éviter les erreurs de cache
fileWatcherType = "none"
headless = true

[client]
# Désactiver l'affichage du bouton de déploiement
showSidebarNavigation = false

[theme]
primaryColor = "#0072B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E3F0FA"
textColor = "#1C1C1C"
font = "sans serif"